name: Generate Snake Game

on:
  schedule:
    # Запускать каждый день в 00:00 UTC
    - cron: "0 0 * * *"
  # Позволяет запускать вручную из вкладки Actions
  workflow_dispatch:
  # Запускать при каждом пуше в main ветку
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      # Шаг 1: Используем готовое действие для генерации змейки
      - name: Generate snake game
        uses: Platane/snk@v3
        with:
          # Используем имя владельца текущего репозитория
          github_user_name: ${{ github.repository_owner }}
          
          # Список файлов для генерации
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.gif?color_snake=orange
      
      # Шаг 2: Загружаем сгенерированные файлы в репозиторий
      - name: Push generated files to the repo
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: main
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
